feat: Allow to minimize the rooms panel.
Icalingua-plus-plus/Icalingua-plus-plus pull request #134
Opened 2022-06-06 11:24 UTC by ForkKILLET

Should close #70

2022-06-06 14:32 UTC, Icalinguaplusplus requested changes

2022-06-06 14:32 UTC, Icalinguaplusplus commented on icalingua/src/renderer/views/ChatView.vue
> +            // 80px: With without avatars
這邊是拼寫錯誤嗎？應該是 width 吧

2022-06-06 16:38 UTC, merged

2022-06-06 23:17 UTC, ForkKILLET commented on icalingua/src/renderer/views/ChatView.vue
> +            // 80px: With without avatars
啊是的

2022-06-25 02:01 UTC, MemoryShadow commented
突然发现，此推送导致在只有头像时不显示消息数量，望修复